### ISSUE TITLE
Feature Request: iOS Support

### ISSUE THREAD

**Issue by coreyarogers** [mannprerak2/nearby_connections#1]
Great work! 👍 

Are there any plans to make this feature available for iOS as well, maybe using [Multipeer Connectivity ](https://developer.apple.com/documentation/multipeerconnectivity) :D ?

**Comment by mannprerak2** [comment]
Hi, sorry for the late response.
I looked into this today.. The thing is that,
Nearby Connections works only for **android** and
Multipeer Connectivity works only for **iOS/ macOS.**

However, for **inter-platform communication**,
there is another API called **[Nearby Messages](https://developers.google.com/nearby/messages/overview)**, 
but it works through the internet and uses _Google Play Services_
