### ISSUE TITLE
file transfer is too slow......

### ISSUE THREAD

**Issue by Luciferamji** [mannprerak2/nearby_connections#17]
I tried the example app with p2p point to point but its still too slow.
I am using this to send large files between 2 devices...

**Comment by mannprerak2** [comment]
Did you turn on location(GPS) on both devices before connecting? 

Otherwise, this may be an issue related to Android Nearby connections => https://github.com/android/connectivity-samples/issues/140
I am closing this issue because it's related to the underlying android package.

**Comment by Luciferamji** [comment]
Hey ,Thanx for your fast reply...
this is to mention that the  file transfer was originally very fast.but the speed reduced drastically between those 2 same devices ,I don't know why (when i rebuild the app from same code base after like 10 days that was previously used) .Yes i tried everything including GPS fine location.

The thing is how it works one time and fails another.(just a doubt )

Thanx in Advace

**Comment by mannprerak2** [comment]
I have no idea, is it that the new apk always is slower? or is it different everytime?

**Comment by Luciferamji** [comment]
No its no different every time.But max speed with which it can transfer is 2 -3 MBps rather than 7-8 MBps which was showing previously.I really don't know why this happened....

and by the way point to point is the one that we should choose right while sending large data files...
 
Thanks in advance.
Its underlying issue with google library and we cant do anything about it .Thanks for you humble reply.

**Comment by ghanimkhan** [comment]
This is the same issue with you want to try how slow it is I have implemented in my try https://play.google.com/store/apps/details?id=com.androxus.sharetez and why are they not updating the library

**Comment by mannprerak2** [comment]
Hi @ghanimkhan 
Very cool app!
Is your app made with flutter? and using this package?
or is it a native android app using android nearby connection library?

**Comment by ghanimkhan** [comment]
Thanks man it's not flutter just used the nearby librery thought this would
be fine but it sucks

**Comment by mannprerak2** [comment]
Oh well, that's true a lot of devices don't get good speeds using this library. But I suppose you can connect devices using a hotspot for file transfer.

- You can first connect using nearby connections library,
- send the information about hotspot name, password, files
- Then programtically make a hotspot on advertiser and use the stored info on discoverer to connect the devices
- Then download the files on the device

But ofcourse that's a way too much effort, might as well wait for them to improve nearby connections
