### ISSUE TITLE
how to Check no. of bytes send while sending the file

### ISSUE THREAD

**Issue by Luciferamji** [mannprerak2/nearby_connections#18]
hey ,

i am unable to figure out how we can figure out no. of bytes sent .
While receiving it works perfectly fine in accept connection();

it appears its running on payloadtransfer update but not the one present in accept connection();
Thanks in advance..
![errror](https://user-images.githubusercontent.com/38823529/90063365-e7fed000-dd06-11ea-895f-6ced5919ade3.png)

**Comment by mannprerak2** [comment]
Is it only running for the receiver side and not the sender side?

**Comment by Luciferamji** [comment]
yes while receiving both function runs. but while sending file they don't seem to run.

**Comment by Luciferamji** [comment]
import 'dart:typed_data';
import 'package:liquid_progress_indicator/liquid_progress_indicator.dart';
import "package:flutter/material.dart";
import "package:nearby_connections/nearby_connections.dart";
import "dart:io";
import 'package:file_picker/file_picker.dart';

class SendReceiveFileScreen extends StatefulWidget {
  final args;

  const SendReceiveFileScreen(this.args);

  @override
  _SendReceiveFileScreenState createState() => _SendReceiveFileScreenState();
}

class _SendReceiveFileScreenState extends State<SendReceiveFileScreen> {
  Map<String, double> incomingFiles = {};
  File tempFile; //reference to the file currently being transferred
  Map<int, String> map = Map();
  @override
  void initState() {
    super.initState();
    acceptConnection();
  }

  void acceptConnection() async {
    Nearby().acceptConnection(
      widget.args,
      onPayLoadRecieved: (endid, payload) async {
        if (payload.type == PayloadType.BYTES) {
          String str = String.fromCharCodes(payload.bytes);
          // print(endid + ": " + str);

          if (str.contains(':')) {
            // used for file payload as file payload is mapped as
            // payloadId:filename

            int payloadId = int.parse(str.split(':')[0]);
            String fileName = (str.split(':')[1]);
            this.setState(() {
              incomingFiles["$fileName"] = 0;
            });
            if (map.containsKey(payloadId)) {
              if (await tempFile.exists()) {
                tempFile.rename(tempFile.parent.path + "/" + fileName);
              } else {
                print("File doesnt exist");
              }
            } else {
              //add to map if not already
              map[payloadId] = fileName;
            }
          }
        } else if (payload.type == PayloadType.FILE) {
          print(endid + ": File transfer started");
          tempFile = File(payload.filePath);
        }
      },
      onPayloadTransferUpdate: (endid, payloadTransferUpdate) {
        print("hello");
        String name = map[payloadTransferUpdate.id];
        // print(name + "kadnlandlk");
        if (payloadTransferUpdate.status == PayloadStatus.IN_PROGRRESS) {
          // print(payloadTransferUpdate.id.toString() + "abcdefg");
          this.setState(() {
            incomingFiles[name] = (payloadTransferUpdate.bytesTransferred /
                payloadTransferUpdate.totalBytes);
          });
        } else if (payloadTransferUpdate.status == PayloadStatus.FAILURE) {
          print("failed");
          print(endid + ": FAILED to transfer file");
        } else if (payloadTransferUpdate.status == PayloadStatus.SUCCESS) {
          print(incomingFiles.toString() + "tfytfytfytf");
          this.setState(() {
            incomingFiles[name] = 1;
          });
          // print("success, total bytes = ${payloadTransferUpdate.totalBytes}");

          if (map.containsKey(payloadTransferUpdate.id)) {
            //rename the file now
            String name = map[payloadTransferUpdate.id];
            tempFile.rename(tempFile.parent.path + "/" + name);
          } else {
            //bytes not received till yet
            map[payloadTransferUpdate.id] = "";
          }
        }
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        title: Text("FILE Tansfer"),
        automaticallyImplyLeading: false,
      ),
      body: Column(
        children: <Widget>[
          Container(
            height: 500,
            child: ListView.builder(
              itemBuilder: (_, i) {
                String key = incomingFiles.keys.elementAt(i);
                if (key == null) return Text("no data");
                double value = incomingFiles.values.elementAt(i);
                return _AnimatedLiquidLinearProgressIndicator(
                    value, key, Colors.orange[200]);
              },
              itemCount: incomingFiles.length,
            ),
          ),
          RaisedButton(
            child: Text("Send File Payload"),
            onPressed: () async {
              List<File> files = await FilePicker.getMultiFile();
              int i = 0;
              if (files == null) return;
              while (i != files.length) {
                int payloadId =
                    await Nearby().sendFilePayload(widget.args, files[i].path);

                this.setState(() {
                  incomingFiles[files[i].path.split('/').last] = 0;
                });
                Nearby().sendBytesPayload(
                    widget.args,
                    Uint8List.fromList(
                        "$payloadId:${files[i].path.split('/').last}"
                            .codeUnits));
                i += 1;
              }
            },
          )
        ],
      ),
    );
  }
}

class _AnimatedLiquidLinearProgressIndicator extends StatefulWidget {
  final data;
  final keyx;
  final color;
  const _AnimatedLiquidLinearProgressIndicator(
      this.data, this.keyx, this.color);

  @override
  State<StatefulWidget> createState() =>
      _AnimatedLiquidLinearProgressIndicatorState();
}

class _AnimatedLiquidLinearProgressIndicatorState
    extends State<_AnimatedLiquidLinearProgressIndicator> {
  @override
  Widget build(BuildContext context) {
    // final percentage = widget.data;
    return Center(
      child: Container(
        width: double.infinity,
        height: 75.0,
        padding: EdgeInsets.symmetric(horizontal: 24.0),
        child: LiquidLinearProgressIndicator(
          value: widget.data,
          backgroundColor: Colors.white,
          valueColor: AlwaysStoppedAnimation(widget.color),
          borderRadius: 12.0,
          center: Text(
            widget.keyx,
            style: TextStyle(
              color: Colors.lightBlueAccent,
              fontSize: 20.0,
              fontWeight: FontWeight.bold,
            ),
          ),
        ),
      ),
    );
  }
}

**Comment by mannprerak2** [comment]
Well If you are getting logs of `payloadTransferUpdate` on sender device, that means the dart function for `payloadTransferUpdate` supplied to `acceptConnection` is not being called.

**Comment by Luciferamji** [comment]
so anyhow can i achieve the percentage of file sent .

**Comment by mannprerak2** [comment]
Please check if this is also happening in the example.
Because in example both devices should get a success snackbar.
If they are its probably some issue on your side.

**Comment by Luciferamji** [comment]
Hey its working correctly  .It was error on my part.I am really sorry about.

It was so humble of you that you responded at your earliest .Thanx for you support I am closing this issue

**Comment by mannprerak2** [comment]
Happy to help! 😊
