### ISSUE TITLE
Feature Request (support files & streams)

### ISSUE THREAD

**Issue by asapJ** [mannprerak2/nearby_connections#2]
Read through the docs found  [Here](https://developers.google.com/nearby/connections/overview) 

Can or will the plugin support other forms of data payload?

**Comment by mannprerak2** [comment]
It's under progress.. I'll try to add files first

**Comment by mannprerak2** [comment]
PR's are welcome :)

**Comment by mannprerak2** [comment]
I've added support for files

**Comment by asapJ** [comment]
Nice work!! closing this issue now.🙂
