### ISSUE TITLE
Change Default directory for storing Files

### ISSUE THREAD

**Issue by Luciferamji** [mannprerak2/nearby_connections#20]
I tried it but i was not able to find exact point where we could change the default storage location.

Thanx in advance;;;;

**Comment by mannprerak2** [comment]
You can't, android nearby connections doesn't expose this.
```text
When a file is received, it is saved in the Downloads 
folder (DIRECTORY_DOWNLOADS) on the recipient's 
device with a generic name and no extension. 
```
You can simply move this file to some other location manually.
