### ISSUE TITLE
Star 1:N transfers

### ISSUE THREAD

**Issue by afarre** [mannprerak2/nearby_connections#23]
Hello,

nearby connections should allow for multiple simultaneous connections, yet I don't seem to be able to send a file or a byte payload to two devices at once. Presuming a server A and clients Y and Z, the flow I followed is:

1. Y connects to A.
2. Z connects to A.
3. A sends a file or bytes.
4. Z receives the file or bytes.
5. Y gets nothing.

For testing, after the previous steps I did:

6. Z stops discovering and also stops all endpoints.
7. A sends a file or bytes.
8. Y gets nothing.

Can you both verify if this flow is correct, and if so, check if you manage to send a file or bytes to multiple devices at once please.
Thanks.

**Comment by afarre** [comment]
I just started working in my app, but I intend to implement this feature. Will update this thread when I get it done, as well as implementing the [progess update](https://developers.google.com/nearby/connections/android/exchange-data?authuser=1#progress_updates) on a file transmission and a connected devices list.

**Comment by mannprerak2** [comment]
Hi, @afarre I am closing this issue for now.
If you need any support regarding this, let me know here itself.
