### ISSUE TITLE
Confirming if is an intended TYPO for enum value PayloadStatus.IN_PROGRRESS

### ISSUE THREAD

**Issue by vaishnavmhetre** [mannprerak2/nearby_connections#25]
Appreciate the awesome work warpping api thoroughly to base one!!

I found a typo in one of the enum - `PayloadStatus.IN_PROGRRESS` (referenced below), just wanted to confirm if this is an expected value to be referred from Base Lib or if the fix can be managed from the repo itself.

I'm yet to implement the functionality for Transfer Update in my ongoing app, but just notified as found so as to receive the fix before wiring it up and eventually breaking it after made fixes from repo!!

https://github.com/mannprerak2/nearby_connections/blob/f35a48433417c60a028b4b5a704c7784c119344b/lib/src/defs.dart#L12

Thanks!

**Comment by mannprerak2** [comment]
Hi @vaishnavmhetre 
Yes, this is most likely a typo.

Since this is a breaking change, and not a high priority, the typo fix should be done in the null_safety branch, and then adding a suffix of `.2` on the null_safety version.

A stable version will be released when dart null safety becomes stable itself, which will probably happen by Jan/Feb.

Let me know if you would like to make these changes. otherwise I will fix it soon.

**Comment by vaishnavmhetre** [comment]
Nevertheless, I would be happy to contribute, although this flag wont work if I'm not wrong? But is it currently breaking the function's workability - is it throwing some kind of error?

If so , I will ignore the implementation of it for some time in that case, waiting for your fix and anything more in terms of optimization and have it sorted at that time.

Or if possible, just let me know if I can refer the status flag from base library call, coz any way I have wrapped my own enums and entities identical to implementation, just for accessibility. I'll move on for time being with that or await your fixes and optimizations!

**Comment by mannprerak2** [comment]
> although this flag wont work if I'm not wrong? But is it currently breaking the function's workability - is it throwing some kind of error?

This is merely a typo, everything should work just fine.
