### ISSUE TITLE
Multiple Payload IDs for a single file

### ISSUE THREAD

**Issue by OmiWakode** [mannprerak2/nearby_connections#29]
Hi, I was making a simple file transfer app using this API, while I was trying to update progress of files, I was checking for PayloadStatus and if it was PayloadStatus.SUCCESS, then I'd increment the index to update progress of next file. But, from what I noticed, this API is creating multiple payloads with different payload IDs for a single file; is this normal? If so, is there any other way to track progress of file transfer?

**Comment by mannprerak2** [comment]
The library shouldn't be creating multiple payload IDs for a single file.

> then I'd increment the index to update progress of next file. 

Not sure what you mean by this, but just to let you know the order of different kind of payloads being sent is not guaranteed. You may receive the file payload or the byte payload first.

How file transfer works is that, you need to send the file and the file name separately, that means you have to send 2 payloads. 1 file payload, and 1 byte payload in 
which you will put the file's payload ID and its name. After you received both of these, you then rename the file on the receiver's end. (Checkout the example for this).

So the ideal way for tracking progress would be -
1. Send a file payload (suppose payload id created is 1012 and file name is img.png)
2. Send a byte payload with above info, E.g convert "1012:img.png" to bytes and send.
3. You may receive the file payload or the byte payload first.
4. Decode the byte payloads to get payloadID and file name.
5. When you have received both, you know know which payloadID maps exactly to which file. So you can use onPayloadTransferUpdate to track its progress.
6.

**Comment by mannprerak2** [comment]
I am closing this for now, but feel free to reopen if need be.
