### ISSUE TITLE
Help With Example

### ISSUE THREAD

**Issue by ostensiblycool** [mannprerak2/nearby_connections#3]
Can this run on iOS? I am getting Unhandled Exception: MissingPluginException errors with your example when I run for iOS from Android Studio. I'm wondering if I am missing something or if it will just only run in Android environments. Thank you.

Example:
`Unhandled Exception: MissingPluginException(No implementation found for method stopDiscovery on channel nearby_connections)`

**Comment by mannprerak2** [comment]
No, its for Android only. It is based on Googles Android Nearby Connection library.
