### ISSUE TITLE
Not issue but getting warnings of deprectation

### ISSUE THREAD

**Issue by lohith8099** [mannprerak2/nearby_connections#30]
Hi,

I am getting warnings when i am compiling and  thought you would like to know. 

Note: /Users/lohithsmacbook/.pub-cache/hosted/pub.dartlang.org/nearby_connections-2.0.2/android/src/main/java/com/pkmnapps/nearby_connections/NearbyConnectionsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/lohithsmacbook/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:9: warning: [deprecation] AsyncTask in android.os has been deprecated
import android.os.AsyncTask;
                 ^
/Users/lohithsmacbook/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:121: warning: [deprecation] AsyncTask in android.os has been deprecated
    new AsyncTask<Void, Void, Boolean>() {
        ^
/Users/lohithsmacbook/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:121: warning: [deprecation] AsyncTask() in AsyncTask has been deprecated
    new AsyncTask<Void, Void, Boolean>() {
    ^
/Users/lohithsmacbook/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:123: warning: [deprecation] doInBackground(Params...) in AsyncTask has been deprecated
      protected Boolean doInBackground(Void... voids) {
                        ^
  where Params,Result are type-variables:
    Params extends Object declared in class AsyncTask
    Result extends Object declared in class AsyncTask
/Users/lohithsmacbook/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:121: warning: [deprecation] AsyncTask() in AsyncTask has been deprecated
    new AsyncTask<Void, Void, Boolean>() {
                                         ^
/Users/lohithsmacbook/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:128: warning: [deprecation] onPostExecute(Result) in AsyncTask has been deprecated
      protected void onPostExecute(Boolean value) {
                     ^
  where Result is a type-variable:
    Result extends Object declared in class AsyncTask
/Users/lohithsmacbook/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:131: warning: [deprecation] execute(Params...) in AsyncTask has been deprecated
    }.execute();
     ^
  where Params,Progress,Result are type-variables:
    Params extends Object declared in class AsyncTask
    Progress extends Object declared in class AsyncTask
    Result extends Object declared in class AsyncTask
7 warnings

**Comment by mannprerak2** [comment]
Thanks for pointing this out, I will try to fix these as soon as I can.

**Comment by mannprerak2** [comment]
Fixed in https://github.com/mannprerak2/nearby_connections/commit/6039334d48f53ce1095f601fd62a0d3da525040a

@lohith8099 
This hasn't been publish yet, but if you want to test this out you can do this in pubspec.yaml
```yaml
nearby_connections:
    git:
      url: git://github.com/mannprerak2/nearby_connections.git
      ref: 6039334
```
make sure to run **`flutter clean`** before running.
