### ISSUE TITLE
Folder name and Rename issue

### ISSUE THREAD

**Issue by devalanrs** [mannprerak2/nearby_connections#31]
How to change the floder name 'nearby' sometimes rename is not working

**Comment by mannprerak2** [comment]
You need to ask for READ/WRITE permission on runtime.

```dart
// Checsk if permission is given
bool b = Nearby().checkExternalStoragePermission();

// Asks for permission
Nearby().askExternalStoragePermission() ;
```

Also, renaming the `Nearby` folder doesn't mean subsequent files will be saved in that folder. Files will always be initially stored in `Downloads/Nearby` folder. Ideally, you should create your own folder and move the files to that location after transfer has completed.
