### ISSUE TITLE
Feature Request: RSSI value

### ISSUE THREAD

**Issue by faheem4797** [mannprerak2/nearby_connections#38]
Please add a feature to calculate the rssi value of the discovered device. Or if there already is a solution to this here please point me towards it. Thank you.

**Comment by mannprerak2** [comment]
I am not sure what RSSI value is. You can also checkout the documentation of android nearby connections, since this is only a wrapper.

**Comment by mannprerak2** [comment]
I think you can probably use this package to get the wifi signal strength https://pub.dev/packages/wifi_info_plugin#-readme-tab-

**Comment by mannprerak2** [comment]
An android based solution for this is mentioned here: https://stackoverflow.com/a/33953371/7186086

Since this feature is not really in scope of this package, I'm closing this.
