### ISSUE TITLE
platformexception(failure 8032: MISSING PERMISSION ACCESS_WIFI_STATE,null,null ) 

### ISSUE THREAD

**Issue by kalyankumar111** [mannprerak2/nearby_connections#39]
its showing platform exception(failure 8032: MISSING PERMISSION ACCESS_WIFI_STATE, null,null ) When you click on start discovery

**Comment by mannprerak2** [comment]
Hi @kalyankumar111, Did you add the relevant permissions in your manifest file? See
https://github.com/mannprerak2/nearby_connections#set-permissions

**Comment by kalyankumar111** [comment]
There are so many AndroidManifest.xml, can you tell me where should I add it

**Comment by mannprerak2** [comment]
Check the example folder. Specifically this file - https://github.com/mannprerak2/nearby_connections/blob/master/example/android/app/src/main/AndroidManifest.xml

**Comment by kalyankumar111** [comment]
Thanks, I'll check it out.

**Comment by mannprerak2** [comment]
Closing this now, feel free to comment here if need be.
