### ISSUE TITLE
compileSdkVersion is set to 28 - Causing Build error

### ISSUE THREAD

**Issue by SherwinJames** [mannprerak2/nearby_connections#40]
Your compile version in your build.gradle for Android is set to  "compileSdkVersion 28", causing compile errors:

```
C:\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nearby_connections-3.1.0\android\src\main\java\com\pkmnapps\nearby_connections\NearbyConnectionsPlugin.java:448: error: cannot find symbol
                if (VERSION.SDK_INT < VERSION_CODES.Q
```)

Can you fix?

**Comment by mannprerak2** [comment]
Hi, could you try running the example app, if it works, there's probably some misconfiguration. You can compare your pubspec.yaml file with the one is example.

**Comment by mannprerak2** [comment]
If you really think this might be because of compile sdk 28, would you consider creating a PR for that?

**Comment by SherwinJames** [comment]
> If you really think this might be because of compile sdk 28, would you consider creating a PR for that?

Flooded with work at the moment, not sure when I'll be able to get to that.  For now I just changed the local cached copy of your plugin build.gradle file from compileSdkVersion 28 to 30, and that solves the compile issue (temporarily).  By the way my applications pubspec.yaml matches you example pubspec.yaml (with regard to the sdk version:   nearby_connections: ^3.1.0
)

**Comment by mannprerak2** [comment]
Cool, I'll try to update this ASAP.

**Comment by mannprerak2** [comment]
Closing this since it has already been completed.
