### ISSUE TITLE
Error 8038: Unknown status code

### ISSUE THREAD

**Issue by Jwiggiff** [mannprerak2/nearby_connections#41]
Title pretty much says it all. I'm getting this error when trying to initiate NFC on my pixel 6. Here's the full error:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(Failure, 8038: unknown status code: 8038, null, null)
E/flutter (12996): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:607
E/flutter (12996): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:177
E/flutter (12996): <asynchronous suspension>
E/flutter (12996): #2      Nearby.startAdvertising
package:nearby_connections/src/nearby.dart:227
```

**Comment by mannprerak2** [comment]
Seems to be a permission issue on Android 12. 

Could you try this solution posted on stackoverflow - https://stackoverflow.com/a/70318674/7186086

**Comment by Jwiggiff** [comment]
So I added the permissions they mentioned in that post. However, I'm still getting the error. I was reading through the docs on the new permissions and it seems like I need to specifically request these permissions, not just put them in the manifest file, I think similar to how I request the location permissions through the `Nearby().askLocationPermissions()` function.

**Comment by mannprerak2** [comment]
I have published a new version with Android 12 fixes- https://pub.dev/packages/nearby_connections/versions/3.2.0.

The `compileSdkVersion` may need to be set to 32 for applications though.
