### ISSUE TITLE
ConnectionInfo.endpointName doesn't work right

### ISSUE THREAD

**Issue by mavyfaby** [mannprerak2/nearby_connections#43]
When requesting a connection, the `receiver`'s `ConnectionInfo.endpointName` points the itself not the `sender`'s endpointName.

**Comment by mannprerak2** [comment]
Hi @mavyfaby, can you give some more details, I am unable to reproduce this.

Here's a screenshot from my devices running the example app, you can see that they do infact show the correct endpoint names

Receiver (3243)
![Screenshot_20220410-142738](https://user-images.githubusercontent.com/31154435/162610780-e3a8acc1-a7b4-4725-8231-1cf853da7585.jpg)

Sender (3259)
![IMG-20220410-WA0002](https://user-images.githubusercontent.com/31154435/162610828-0fce35a5-86a9-4990-85a3-bca53b5c6cff.jpg)

**Comment by mavyfaby** [comment]
Hi @mannprerak2, I also tried the example app and it's working fine. Maybe my code is incorrect and I've to found it out. Thanks.

**Comment by mavyfaby** [comment]
Hi @mannprerak2, I tested the example app and it's working fine. Maybe my code is incorrect though.

**Comment by mavyfaby** [comment]
I've found out the problem:


When I do `requestConnection`, I passed the receiver's name instead of the current's (sender's) name in the first parameter.

### The problem

```dart
await Nearby().requestConnection(
   userName, // receiver's name
   id, // receiver's id
);
``` 

### Solved

```dart
await Nearby().requestConnection(
   deviceName, // Sender's name or the current device's name
   id, // receiver's id
);
```

Maybe the docs isn't clear for me though. Also, maybe I'll make a PR to make the docs clear. 

Btw, Thanks for this awesome library!

**Comment by mavyfaby** [comment]
I've found out the problem: When I `requestConnection`, I passed the receiver's name instead of the current's (sender's) name in the first parameter.

### The problem

```dart
await Nearby().requestConnection(
   userName, // receiver's name
   id, // receiver's id
);
``` 

### Solved

```dart
await Nearby().requestConnection(
   deviceName, // Sender's name or the current device's name
   id, // receiver's id
);
```

Maybe the docs isn't clear for me though. 

Btw, Thanks for this awesome library!

**Comment by mavyfaby** [comment]
I've found out the problem:

When I do `requestConnection`, I passed the receiver's name instead of the current device's name in the first parameter.

### The problem

```dart
await Nearby().requestConnection(
   userName, // receiver's name
   id, // receiver's id
);
``` 

### Solved

```dart
await Nearby().requestConnection(
   deviceName, // Sender's name or the current device's name
   id, // receiver's id
);
```

Maybe the docs isn't clear for me though.

Btw, Thanks for this awesome library!

**Comment by mannprerak2** [comment]
Nice work!
