### ISSUE TITLE
OnEndpointFound/OnEndpointLost functions not working properly

### ISSUE THREAD

**Issue by VTapp1** [mannprerak2/nearby_connections#46]
`  void advertise(String name) async {
      try {
       bool ad = await Nearby().startAdvertising(
          name,
          strategy,
          onConnectionInitiated: onConnectionInit,
          onConnectionResult: (id, status) {
            print(status);
          },
          onDisconnected: (id) {
            print("Disconnected: ${endpointMap[id]!.endpointName}, id $id");
          },
          serviceId: "com.test.app",
        );
        print(ad);
      } catch (exception) {
        print(exception);
      }
  }`

`  void discover(String userName) async {
    bool connected=false;
      try {
        bool disc = await Nearby().startDiscovery(
          userName,
          strategy,
          onEndpointFound: (id, name, serviceId) {
            print("Id:" + id);
            print("Name:" +name);
            print("Service:" + serviceId);
          },
          onEndpointLost: (id) {
            print("Lost discovered Endpoint: id $id");
          },
          serviceId: "com.test.app",
        );
        print("DISCOVERING using : "+ userName +" "+ disc.toString());
        print(strategy);
      } catch (e) {
        print(e);
      }
  }`

Everything is working fine but the function doesn't print the info above. Idk what's causing this to be honest. It only prints OnEndpointFound or OnEndpointLost in the console. 

![image](https://user-images.githubusercontent.com/101049656/170591740-df77de9f-b949-4d22-a158-7bb1c1b60426.png)

**Comment by mannprerak2** [comment]
So to sum up, are the dart functions not being called? yet the internal debug logs of nearby_connection are being triggered?

**Comment by VTapp1** [comment]
Yes exactly, it was working fine but idk what happened. Do you have any idea what's causing this?

**Comment by mannprerak2** [comment]
Is it possible the debug output is not showing print statement? maybe try debugPrint here or run this via terminal

**Comment by VTapp1** [comment]
I tried but it didn't work too. After looking more into this, I found that the Flutter Cloud Messaging service I added to the app for push notifications messed up with your plugin somehow, nearby executes but doesn't call the OnEndpointFound/ OnEndpointLost functions at all. But when I remove it it works normally. What do you think about this? 

Here's the code:

![code](https://user-images.githubusercontent.com/101049656/170866856-33fee501-52a6-42c3-b678-331f32d0e354.png)

**Comment by mannprerak2** [comment]
Ah so it's this one again.

There's an open flutter issue regarding this - https://github.com/flutter/flutter/issues/23904

For possible workarounds, you can read the comments by the community here - https://github.com/mannprerak2/nearby_connections/issues/36

**Comment by VTapp1** [comment]
Thanks a lot man! I finally understand what's actually causing this. I'll checkout the threads you've linked and see what I can do about it.
