### ISSUE TITLE
Transfers only via Bluetooth.

### ISSUE THREAD

**Issue by krypticallusion** [mannprerak2/nearby_connections#5]
Hi, I've been using this plug-in for a while now, however it seems like it only transfers file over Bluetooth and not WiFi-Direct/Hotspot as Nearby connections should. Any views on this?

**Comment by mannprerak2** [comment]
What strategy are you using?
This is only a wrapper of the Android Nearby connections API by google 
It uses both hotspot, common wifi(if available)and Bluetooth automatically based on behaviour defined by google for different strategies of connection.
I have tested this using p2p_star strategy and it does use hotspot for that.

**Comment by krypticallusion** [comment]
I've tried P2P_STAR and P2P_POINT_TO_POINT
Both transferred a file(5mB) with Bluetooth.

**Comment by mannprerak2** [comment]
@krypticallusion Can u try a larger file?
The nearby connections API is known to switch between connections automatically.
P.S And I don't think you can do anything about its behavior. This package is merely a wrapper.

**Comment by krypticallusion** [comment]
Hmm, I transferred a 60mB file. It transferred with Bluetooth for 15mB which was half an hour, then switched to WiFi direct
