### ISSUE TITLE
 Is it possible to set it to connect only through Bluetooth without connecting to wifi?

### ISSUE THREAD

**Issue by kimdindoo** [mannprerak2/nearby_connections#54]
Hi, Thanks for making such a nice library.
Is it possible to set it to connect only through Bluetooth without connecting to wifi?

**Comment by mannprerak2** [comment]
The library has no input option which allows us to decide the communication medium. So it's not feasible directly.

However I found this on SO, it's probably worth a try, but I cannot say if this behaviour is consistent across devices or android versions
SO link: https://stackoverflow.com/questions/47273842/bluetooth-only-connection-with-nearby-communication

**Comment by kimdindoo** [comment]
Thank you for the quick reply. Even so, I also read that article and tested it, and it seems to work well with Bluetooth connection.
