### ISSUE TITLE
location activated with enableLocationServices() is always on "Battery saving" mode

### ISSUE THREAD

**Issue by sd-timaru** [mannprerak2/nearby_connections#55]
Hi, Thank you for this great package. For my project is working very well, except for one part: if the user activates the location with the enableLocationServices() convenience method, the location mode is always "Battery saving". If afterwards the user opens another app which uses the location (an navigation app, for example), the nav app will have problem getting the precise location.
It is possible that the convenience method enables the location with "High accuracy" mode?

**Comment by mannprerak2** [comment]
Sorry but that's out of scope for this package. But you should easily be able to switch.

It'd recommend switching to https://pub.dev/packages/permission_handler for handling any permissions.

The convenience methods will be deprecated soon and removed in the next major release.
