### ISSUE TITLE
Android: Null context is not permitted.

### ISSUE THREAD

**Issue by devNamanGor** [mannprerak2/nearby_connections#56]
Problem: A NullPointerException occurs when calling enableLocationServices

Also, even if I enable location, Wi-Fi and Bluetooth manually, the code works and onEndpointFound is executed on the native side, but the flutter side callback isn't called.

<details>
<summary>Error Log</summary>

```
E/MethodChannel#nearby_connections( 4547): Failed to handle method call
E/MethodChannel#nearby_connections( 4547): java.lang.NullPointerException: Null context is not permitted.
E/MethodChannel#nearby_connections( 4547): 	at com.google.android.gms.common.internal.Preconditions.checkNotNull(com.google.android.gms:play-services-basement@@18.1.0:2)
E/MethodChannel#nearby_connections( 4547): 	at com.google.android.gms.common.api.GoogleApi.<init>(com.google.android.gms:play-services-base@@18.1.0:4)
E/MethodChannel#nearby_connections( 4547): 	at com.google.android.gms.common.api.GoogleApi.<init>(com.google.android.gms:play-services-base@@18.1.0:1)
E/MethodChannel#nearby_connections( 4547): 	at com.google.android.gms.internal.location.zzce.<init>(com.google.android.gms:play-services-location@@21.0.1:1)
E/MethodChannel#nearby_connections( 4547): 	at com.google.android.gms.location.LocationServices.getSettingsClient(com.google.android.gms:play-services-location@@21.0.1:1)
E/MethodChannel#nearby_connections( 4547): 	at com.pkmnapps.nearby_connections.LocationHelper.requestLocationEnable(LocationHelper.java:97)
E/MethodChannel#nearby_connections( 4547): 	at com.pkmnapps.nearby_connections.NearbyConnectionsPlugin.onMethodCall(NearbyConnectionsPlugin.java:114)
E/MethodChannel#nearby_connections( 4547): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#nearby_connections( 4547): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#nearby_connections( 4547): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#nearby_connections( 4547): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#nearby_connections( 4547): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#nearby_connections( 4547): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#nearby_connections( 4547): 	at android.os.Looper.loopOnce(Looper.java:210)
E/MethodChannel#nearby_connections( 4547): 	at android.os.Looper.loop(Looper.java:299)
E/MethodChannel#nearby_connections( 4547): 	at android.app.ActivityThread.main(ActivityThread.java:8252)
E/MethodChannel#nearby_connections( 4547): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#nearby_connections( 4547): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
E/MethodChannel#nearby_connections( 4547): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
E/flutter ( 4547): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Null context is not permitted., null, java.lang.NullPointerException: Null context is not permitted.
E/flutter ( 4547): 	at com.google.android.gms.common.internal.Preconditions.checkNotNull(com.google.android.gms:play-services-basement@@18.1.0:2)
E/flutter ( 4547): 	at com.google.android.gms.common.api.GoogleApi.<init>(com.google.android.gms:play-services-base@@18.1.0:4)
E/flutter ( 4547): 	at com.google.android.gms.common.api.GoogleApi.<init>(com.google.android.gms:play-services-base@@18.1.0:1)
E/flutter ( 4547): 	at com.google.android.gms.internal.location.zzce.<init>(com.google.android.gms:play-services-location@@21.0.1:1)
E/flutter ( 4547): 	at com.google.android.gms.location.LocationServices.getSettingsClient(com.google.android.gms:play-services-location@@21.0.1:1)
E/flutter ( 4547): 	at com.pkmnapps.nearby_connections.LocationHelper.requestLocationEnable(LocationHelper.java:97)
E/flutter ( 4547): 	at com.pkmnapps.nearby_connections.NearbyConnectionsPlugin.onMethodCall(NearbyConnectionsPlugin.java:114)
E/flutter ( 4547): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter ( 4547): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 4547): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter ( 4547): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 4547): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter ( 4547): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 4547): 	at android.os.Looper.loopOnce(Looper.java:210)
E/flutter ( 4547): 	at android.os.Looper.loop(Looper.java:299)
E/flutter ( 4547): 	at android.app.ActivityThread.main(ActivityThread.java:8252)
E/flutter ( 4547): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 4547): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
E/flutter ( 4547): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
E/flutter ( 4547): )
E/flutter ( 4547): #0      StandardMethodCodec.decodeEnvelope
message_codecs.dart:652
E/flutter ( 4547): #1      MethodChannel._invokeMethod
platform_channel.dart:310
E/flutter ( 4547): <asynchronous suspension>
E/flutter ( 4547): #2      Nearby.enableLocationServices
nearby.dart:192
```

</details>

Edit: Btw, thank you very much for this library! Its a awesome bit-of-kit! Great work!

**Comment by mannprerak2** [comment]
The convenience methods for runtime permissions/enabling location etc might not work in situations like the activity being in the background.
And may not work even on lower or latest Android versions properly.

I'd suggest you to switch over to another package to handle these (as mentioned in the readme as well) such as the [permission_handler](https://pub.dev/packages/permission_handler) package, which is maintained and would work for almost android versions.

I'm thinking about deprecating and then removing those methods with a major version change.

**Comment by devNamanGor** [comment]
Well just to clarify, the activity is not in the background, and the app is running on Android 13, which might be the cause. And yes, I will change to permission_handler package, thank you for that. 

But on deeper investigation, i found that the `onAttachedToActivity` method is not called at all, which is leading the activity to be null. And even if I turn on the Bluetooth, Wi-Fi and location myself, the `onEndpointFound` is called only on the native side, and the method provided as the callback on flutter side isn't called at all. This might be due to Android 13, but it doesn't seem plausible as the native callbacks are working, just that the callbacks on the flutter side aren't. I tried to search more about this but couldn't find anything.

**Comment by mannprerak2** [comment]
Do you happen to be using another package which runs dart code in the background? (Such as firebase push notifications)

See this for details: https://github.com/flutter/flutter/issues/23904

**Comment by devNamanGor** [comment]
Yes I am using FCM and it does execute headless dart code, thank you for the link to the issue! I'll check it out ASAP and get back!

**Comment by devNamanGor** [comment]
So I looked into the issue, and found not using the `onBackgroundMessage` fixes the issue. And so I removed it.

But there's one more thing I recommend, you could not remove the convenience methods, as for example, in my case, the convenience methods enable me to request the permissions without an extra dependency. Also, there's just one problem for the current permissions method for Android. If the `NEARBY_WIFI_DEVICES` permissions could be added while requesting the location permissions, the convenience methods work just fine on Android 13 too. 

The only changes that need to be done are in the `checkLocationPermission` function in the Plugin class and the `requestLocationPermission` method in the location helper class.

Once again, Thank you very much for the help in the issue and for providing this awesome package!

**Comment by mannprerak2** [comment]
> the convenience methods enable me to request the permissions without an extra dependency

That was the intent, but you answered why it should still be removed in the comment itself 😛 

It's basically less maintainence in this package for the ever changing Android ecosystem.

I'll make sure to update the examples and add helpful links to replace the deprecated code's dart doc for a smoother transition.

Closing this issue now.
