### ISSUE TITLE
onEndpointFound never called

### ISSUE THREAD

**Issue by sd-timaru** [mannprerak2/nearby_connections#6]
Hi!
I want to use your plugin in my app, but i have a problem: after Nearby().startDiscovery(), in the console i find :

D/nearby_connections( 4515): startDiscovery
D/nearby_connections( 4515): onEndpointFound

but the  onEndpointFound method from my app is never called. In fact, the _channel.setMethodCallHandler method from nearby_connections.dart is never called.

The example app from your plugin is working fine, it seems that is some sort of conflict between this plugin and other plugin from my app, but i don't know which.

Please, do you have any idea on how to solve this?
Thank you very much!

Later edit:

I found the plugin that conflicts with this one, is firebase_messaging, particularly this method:

```
  public static void startBackgroundIsolate(Context context, long callbackHandle) {
    FlutterMain.ensureInitializationComplete(context, null);
    String appBundlePath = FlutterMain.findAppBundlePath();
    FlutterCallbackInformation flutterCallback =
        FlutterCallbackInformation.lookupCallbackInformation(callbackHandle);
    if (flutterCallback == null) {
      Log.e(TAG, "Fatal: failed to find callback");
      return;
    }

    // Note that we're passing `true` as the second argument to our
    // FlutterNativeView constructor. This specifies the FlutterNativeView
    // as a background view and does not create a drawing surface.
    backgroundFlutterView = new FlutterNativeView(context, true);
    if (appBundlePath != null && !isIsolateRunning.get()) {
      if (pluginRegistrantCallback == null) {
        throw new RuntimeException("PluginRegistrantCallback is not set.");
      }
      FlutterRunArguments args = new FlutterRunArguments();
      args.bundlePath = appBundlePath;
      args.entrypoint = flutterCallback.callbackName;
      args.libraryPath = flutterCallback.callbackLibraryPath;
      backgroundFlutterView.runFromBundle(args);
      pluginRegistrantCallback.registerWith(backgroundFlutterView.getPluginRegistry());
    }
  }
```

Unfortunately, i don't know how to solve this....

**Comment by mannprerak2** [comment]
Hi @sd-timaru 
> In fact, the _channel.setMethodCallHandler method from nearby_connections.dart is never called.

The Nearby Class is a singleton, it is called only the first time when you call Nearby() in the factory constructor `Nearby._()`

The method channels should not interfere as its clearly stated in the documentation of platform_channel, the method channels are given a different name
> /// The logical identity of the channel is given by its name. Identically named
/// channels will interfere with each other's communication.

How did you get to the conclusion of the firebase_messaging function interference?

Also, if you haven't already, can you try adding a print statement to the method handler function in `_channel.setMethodCallHandler` like this

```dart
Nearby._() {
    _channel.setMethodCallHandler((handler) {
     print(handler.method); // add this line to check
      Map<dynamic, dynamic> args = handler.arguments;
      switch (handler.method) {
     .
     .
     .
```

**Comment by sd-timaru** [comment]
Hi **@mannprerak2**

> How did you get to the conclusion of the firebase_messaging function interference?

firebase_messaging init method looks like this:

```
     fcm = FirebaseMessaging();
      if (Platform.isIOS){
        fcm.requestNotificationPermissions(const IosNotificationSettings(sound: true, badge: true, alert: true));
        fcm.onIosSettingsRegistered.listen((IosNotificationSettings settings) {
        });
      }
   // }

    fcm.configure(
      onMessage: (Map<String, dynamic> message) async {
        print('on message $message');
        await myForegroundMessageHandler(message);
      },
      onResume: (Map<String, dynamic> message) async {
        print('on resume $message');
        await myForegroundMessageHandler(message);
      },
      onLaunch: (Map<String, dynamic> message) async {
        print('on launch $message');
        await  myForegroundMessageHandler(message);
      },
      onBackgroundMessage: myBackgroundMessageHandler,
    );
```

If i comment this line:
``` //onBackgroundMessage: myBackgroundMessageHandler,```

onEndpointFound is called, otherwise not....

**Comment by mannprerak2** [comment]
I found an [issue](https://github.com/flutter/flutter/issues/23904) on the flutter repo

**Comment by mannprerak2** [comment]
As I could extract from the conversation from the above-mentioned issue
You can clone the firebase_messaging plugin, add it manually and do this =>

Omitting the call to `pluginRegistrantCallback.registerWith(backgroundFlutterView.getPluginRegistry());` 

this allows the both the headless and main channel to work, however, this would prevent headless code on the Dart from using other plugins.

So if you don't plan to call any other plugin code in you `myBackgroundMessageHandler` function then I suppose this solution might work for you

**Comment by sd-timaru** [comment]
> Omitting the call to pluginRegistrantCallback.registerWith(backgroundFlutterView.getPluginRegistry());

is not working, i receive this when i start the app:

```E/flutter (11359): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method FcmDartService#initialized on channel plugins.flutter.io/firebase_messaging_background)```

**Comment by mannprerak2** [comment]
well unfortunately, this issue needs to be fixed by the flutter team.
I can only reccomend not using the background channel as no other plugin (which uses platform channel) will work if you decide to use the background message channel of firebase_messaging.

**Comment by sd-timaru** [comment]
I must use background channel! And i use other plugins that have platform channels without problems.  It seems that only plugins with callback handlers are not working....

**Comment by mannprerak2** [comment]
Well, the issue lies in calling dart code from android code.
Perhaps you can write platform code yourself that doesn't require you to communicate data back to dart code by using method call handler.. but ofcourse this will be tedious.

**Comment by mpiparo** [comment]
hi all.  just bringing this back from the dead to check if there has been any progress on the flutter front anyone is aware of that could help resolve this issue - @sd-timaru, were you ever able to resolve or come up with an alternate solution?   i'm having the exact same problem - I need to use background handling in firebase_messaging while also receiving nearby_connections onEndpointFound callbacks. thanks.

**Comment by GanisDev** [comment]
I think I found an temporary solution.... When I need nearby functionality in my app I ask the user to restart the app. Before restart, I save in SharedPreferences:

bool isNearbyRequested  = true

When the app starts it checks that bool. If is set to true, is not registering the onBackgroundMessage from the FirebaseMessaging:

void main() async {
 WidgetsFlutterBinding.ensureInitialized();
 await Firebase.initializeApp( options: DefaultFirebaseOptions.currentPlatform);
 SharedPreferences sharedPrefs = await SharedPreferences.getInstance();
 bool isNearbyRequested = sharedPrefs.getBool('${appStorageKey}isNearbyRequested') ?? false;
 if(!isNearbyRequested){
  FirebaseMessaging.onBackgroundMessage(myBackgroundMessageHandler);
 }
 runApp(const App());
}

With this solution, both plugins work.

But, in order for the FirebaseMessaging to function (in foreground and in the background) is necessary that 

FirebaseMessaging.onBackgroundMessage(myBackgroundMessageHandler);

to be run at least one time.

**Comment by mannprerak2** [comment]
Now that the referenced flutter issue is closed you should be able to call Plugins from another isolate.

Checkout https://medium.com/flutter/introducing-background-isolate-channels-7a299609cad8

**Comment by tusharaddeveloper** [comment]
when i am using firebase_messaging and nearby_connection then erroe occurs coming 

=> PlatformException(error, Attempt to invoke virtual method 'void android.app.Activity.requestPermissions(java.lang.String[], int)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.requestPermissions(java.lang.String[], int)' on a null object reference
