### ISSUE TITLE
onEndpointLost not called on the discoverer side when advertiser stops advertising

### ISSUE THREAD

**Issue by sarbogast** [mannprerak2/nearby_connections#61]
First of all, thanks a lot for this super useful plugin. Exactly what I needed.
But I'm having an issue with discovery. I have 2 devices using the STAR strategy.
One is the advertiser, one is the discoverer, and the discoverer shows a list of available advertisers maintained thanks to `onEndpointFound` and `onEndpointLost` callbacks. However, even though `onEndpointFound` is called on the discoverer side when the advertiser starts advertising, `onEndpointLost` doesn't seem to be called when advertiser stops advertising. And that is before any connection is established. 
Is there anything else I should do on the advertiser side to notify the discoverer that I'm not there anymore?

I looked at other issues mentioning something similar, and I'm not using any Firebase Cloud Messaging dependency that could interfere. I am using other Firebase dependencies like storage and firestore, but not cloud messaging.

**Comment by sarbogast** [comment]
And I was able to reproduce the same problem with the example app: I added a `debugPrint` just before `showSnackbar` in `onEndpointLost` in main.dart, just in case the panel to request connection could block the snackbar, and when I stop advertising on the advertiser, `onEndpointLost` is not called on the discoverer.

**Comment by sarbogast** [comment]
I put together [a simple demo app](https://github.com/sarbogast/nearby_connections_demo) that replicates the issue.

1. Launch the app on 2 Android devices
2. On the first device, tap the "Discoverer" button to put the device in discovering mode
3. On the first device, tap the "Start discovery" button and accept permissions
4. On the second device, tap the "Advertiser" button to put the device in advertising mode
5. On the second device, tap the "Start advertising" button and accept permissions
6. Second device's endpoint id shows up on first device
7. On the second device, tap "Stop advertising"
8. On the first device, onEndpointLost is not called, even when waiting for a while, so list of discovered endpoints is not updated

**Comment by mannprerak2** [comment]
Hi @sarbogast thanks for reporting this.

I was able to reproduce the same as well, it seems like this might be an issue from nearby_connections, even with the latest version (18.7.0)

**Comment by mannprerak2** [comment]
I tried the [NearbyConnectionsWalkieTalkie sample](https://github.com/android/connectivity-samples/tree/main/NearbyConnectionsWalkieTalkie) and kept advertising and stop advertising, but it seems like the onEndpointLost callback is never called.

```java
D/WalkieTalkie: onEndpointFound(endpointId=3X4F, serviceId=com.google.location.nearby.apps.walkietalkie.automatic.SERVICE_ID, endpointName=03927)
I/alkie.automatic: Compiler allocated 4413KB to compile void android.view.ViewRootImpl.performTraversals()
D/WalkieTalkie: onEndpointFound(endpointId=YLFD, serviceId=com.google.location.nearby.apps.walkietalkie.automatic.SERVICE_ID, endpointName=03927)
D/WalkieTalkie: onEndpointFound(endpointId=JAHV, serviceId=com.google.location.nearby.apps.walkietalkie.automatic.SERVICE_ID, endpointName=29343)
D/WalkieTalkie: onEndpointFound(endpointId=YPXP, serviceId=com.google.location.nearby.apps.walkietalkie.automatic.SERVICE_ID, endpointName=95561)
D/WalkieTalkie: onEndpointFound(endpointId=VB79, serviceId=com.google.location.nearby.apps.walkietalkie.automatic.SERVICE_ID, endpointName=71741)
```

**Comment by mannprerak2** [comment]
I've filed https://github.com/google/nearby/issues/1977 in the underlying repo.

**Comment by mannprerak2** [comment]
As per discussions on the referenced issue, seems like the fix will be live around mid-august, will keep this issue open till then.
