### ISSUE TITLE
How sperate out sender and receving bytes progress

### ISSUE THREAD

**Issue by WAQAS039** [mannprerak2/nearby_connections#62]
Hey I am trying to create an application to share file via Using your Plugin. I am stuck in this issue that when we share a filePayload so we do like this 
        int payloadId = await Nearby().sendFilePayload(key, file.path);
        Nearby().sendBytesPayload(key, Uint8List.fromList("$payloadId:${file.path.split('/').last}".codeUnits));

now we r sending file info as well as bytes so in progress it shows progress of both like first file info (ex: file.png) bytes progress which is text and then the bytes progress so it cause confusion so can u tell me how i can i only show progress of bytes not the file info progress and how i can seprate out sender and receiving progress. can u update example code it will really helpfull as i am stuck in this problem from last 2 to 4 days

**Comment by WAQAS039** [comment]
u can update this code
      onPayloadTransferUpdate: (endid, payloadTransferUpdate) {
        print("////////onPayloadTransferUpdate////////");
        if (payloadTransferUpdate.status == PayloadStatus.IN_PROGRESS) {
          print("///////////${(payloadTransferUpdate.bytesTransferred / payloadTransferUpdate.totalBytes) * 100}//////////");
            senderPercentage = (payloadTransferUpdate.bytesTransferred / payloadTransferUpdate.totalBytes) * 100;
            notifyListeners();
        } else if (payloadTransferUpdate.status == PayloadStatus.FAILURE) {
          senderPercentage = 0.0;
          notifyListeners();
        } else if (payloadTransferUpdate.status == PayloadStatus.SUCCESS) {
          senderPercentage = 0.0;
          notifyListeners();
          print("$endid success, total bytes = ${payloadTransferUpdate.totalBytes}");
          /// to do changes here
          if (map.containsKey(payloadTransferUpdate.id)) {
            //rename the file now
            String name = map[payloadTransferUpdate.id]!;
            moveFile(tempFileUri!, name);
          } else {
            /// to do changes here
            //bytes not received till yet
            map[payloadTransferUpdate.id] = "";
          }
        }
      }

**Comment by mannprerak2** [comment]
Hi @WAQAS039 
You can simply compare the payload id. The sendFilePayload function returns an id, which can be used to determine if onPayloadTransferUpdate has been called for the file payload.

Alternatively you can also store the payload id in the onPayloadReceived function if the payloadType is File.

As for the example, I wanted to keep it to a minimum.

**Comment by WAQAS039** [comment]
hey please can u send me some code to have some idea about separate put I'd
of file and payload

**Comment by mannprerak2** [comment]
Here's some rough psuedo code

```dart
String currentFilePayloadId="";

currentFilePayloadId= await Nearby.sendFilePayload(....);

omPayloadTransferUpdate(endpointId, transferUpdate) {
  if (transferUpdate.id ==currentFilePayloadId ) {
    // Show the progress
    ...
  }
}

```

**Comment by WAQAS039** [comment]
Great!
