### ISSUE TITLE
PlatformException(Failure, 17: API: Nearby.CONNECTIONS_API is not available on this device. Connection failed with: ConnectionResult{statusCode=INTERNAL_ERROR, resolution=null, message=null}, null, null)

### ISSUE THREAD

**Issue by kennest** [mannprerak2/nearby_connections#64]
Hello everyone , i got this error when i attempt to discover on xiaomi redmi note 9 pro Android 12. Please help me.

**Comment by mannprerak2** [comment]
You'll need to install play store and play services.

Source: https://stackoverflow.com/a/68066205

**Comment by mhmdelngar** [comment]
faced the same error 
i am having play store and play service installed

**Comment by mhmdelngar** [comment]
alot of people having the same issue  too
https://issuetracker.google.com/issues/299170799

**Comment by mannprerak2** [comment]
From rhe comments on above issue tracker -
> We are cherry-picking a rollback into the current version of Play Services that is rolling out to 100% next Monday, September 25
A proper fix will roll out in Play Services 100% on October 4

**Comment by mhmdelngar** [comment]
yes i saw it 
thanks for this wonderful plugin

**Comment by sd-timaru** [comment]
Until the fix, you can try to downgrade Google Play Services:

[https://dex100c0der.github.io/android-ios-support/dowgrade-gpservices.html](https://dex100c0der.github.io/android-ios-support/dowgrade-gpservices.html)

**Comment by kennest** [comment]
> Until the fix, you can try to downgrade Google Play Services:
> 
> https://dex100c0der.github.io/android-ios-support/dowgrade-gpservices.html

I've try to downgrade and it works now.
