### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by siraiwaqarali** [mannprerak2/nearby_connections#65]
The app was working fine suddenly facing this issue

PlatformException(Failure, 17: API: Nearby.CONNECTIONS_API is not available on this device. Connection failed with: ConnectionResult{statusCode=INTERNAL_ERROR, resolution=null, message=null}, null, null)

I have tried it on multiple devices and it gives this on all devices.

I have play services and play store installed.

**Comment by mannprerak2** [comment]
Duplicate: https://github.com/mannprerak2/nearby_connections/issues/64
