### ISSUE TITLE
Finding Nearby Issue with latest Google Play Service App Update

### ISSUE THREAD

**Issue by Osamakhandart** [mannprerak2/nearby_connections#67]
with the new update of Google play service app. the nearby devices are not finding. it works if I uninstall latest update of Google play service app. this is the error message shown.

PlatformException(Failure, 17: API: Nearby.CONNECTIONS_API is not available on this device.

**Comment by mannprerak2** [comment]
See this for more details - https://github.com/mannprerak2/nearby_connections/issues/64
