### ISSUE TITLE
Provided Example App crashing while transferring  ".MP4" file type or any other "audio/video" file.

### ISSUE THREAD

**Issue by anil-sookshum** [mannprerak2/nearby_connections#7]
I tried running the Example App provided with this repo. Working fine while transferring images(small sizes) and bytes (i.e Text, Strings). When I tried by sending ".mp4" and ".mp3" type files the App is crashing (Without any error log).

**Comment by mannprerak2** [comment]
HI @anil-sookshum 
This isn't an error with the library, but with a third party plugin used in example app

I have Used ImagePicker which is called upon clicking the sendFilePayload Button, like this
```dart
File file =  await ImagePicker.pickImage(source: ImageSource.gallery);
```

So if you select a File which is not an image the ```pickImage()``` method throws an exception causing the App to crash
.
.
.
You can use the [FilePicker package](https://pub.dev/packages/file_picker)
and replace 
```dart
File file =  await ImagePicker.pickImage(source: ImageSource.gallery);
```
with
```dart
File file = await FilePicker.getFile();
```
