### ISSUE TITLE
PlatformException(Failure, 8038: MISSING_PERMISSION_BLUETOOTH_ADVERTISE, null, null)

### ISSUE THREAD

**Issue by krishnanpandya007** [mannprerak2/nearby_connections#71]
When i try to call startAdvertising() method i got following error,
PlatformException(Failure, 8038: MISSING_PERMISSION_BLUETOOTH_ADVERTISE, null, null)
i have included following permissions already in my Manifest.xml file

<uses-permission android:name="android.permission.BLUETOOTH" />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
<uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:minSdkVersion="29" android:name="android.permission.ACCESS_FINE_LOCATION" />

<uses-permission android:minSdkVersion="31" android:name="android.permission.BLUETOOTH_ADVERTISE" />
<uses-permission android:minSdkVersion="31" android:name="android.permission.BLUETOOTH_CONNECT" />
<uses-permission android:minSdkVersion="31" android:name="android.permission.BLUETOOTH_SCAN" />

<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
what can be the problem here??

**Comment by mannprerak2** [comment]
You'll need to request permissions at runtime as well, use the permission_handler packag for this

```
// location permission
await Permission.location.isGranted         // Check
await Permission.location.request()         // Ask

// location enable dialog
await Location.instance.requestService()

// external storage permission
await Permission.storage.isGranted          // Check
await Permission.storage.request()          // Ask

// Bluetooth permissions
bool granted = !(await Future.wait([        // Check
    Permission.bluetooth.isGranted,
    Permission.bluetoothAdvertise.isGranted,
    Permission.bluetoothConnect.isGranted,
    Permission.bluetoothScan.isGranted,
])).any((element) => false);
[                                           // Ask
    Permission.bluetooth,
    Permission.bluetoothAdvertise,
    Permission.bluetoothConnect,
    Permission.bluetoothScan
].request();
```
