### ISSUE TITLE
The example project seams deprecated. 

### ISSUE THREAD

**Issue by saiful00000** [mannprerak2/nearby_connections#76]
Requesting to provide a latest example project.

**Comment by mannprerak2** [comment]
I'm not sure what you mean by deprecated? Can you mention some ways it needs to be updated.

**Comment by saiful00000** [comment]
Sorry to informing that I made a mistake regarding this issue. I suppose to create the issue to another repository. Could you please close this issue? Thanks.

**Comment by saiful00000** [comment]
This issue created by mistake. I am closing it.
