### ISSUE TITLE
Nearby messages api

### ISSUE THREAD

**Issue by alexworeku** [mannprerak2/nearby_connections#8]
Hello,i like the nearby_connection plugin ,please can you make the nearby_messages api plugin  as well

**Comment by mannprerak2** [comment]
Hi @alexworeku 
what is your use case?
> also,
> did you try this https://pub.dev/packages/nearby_messages_api

**Comment by eleomilagrosa** [comment]
https://developers.google.com/android/reference/com/google/android/gms/nearby/messages/MessageListener#onDistanceChanged(com.google.android.gms.nearby.messages.Message

Need a help,

My use case was is to get all devices near to me.
and get all their distance using the "Distance" Class,

please help us expose the listeners in Nearby Messages

**Comment by eleomilagrosa** [comment]
> Hi @alexworeku
> what is your use case?
> 
> > also,
> > did you try this https://pub.dev/packages/nearby_messages_api

This one they did not include all the callback.
I'll ask the owner of the library first

**Comment by mannprerak2** [comment]
You can fork that package and implement it on your own.
You can use my package for details of how to automatically call a dart function from a java function.
See the `onPayloadTransferUpdate` method

**Comment by alexworeku** [comment]
Hello,my case is that i wanted to detect nearby devices,i know the nearby
connections works well,but not for my case,when i search in google it says
nearby can connect only 6 devices at most.but i wanted to do more.and i
have tried that plugin.it does not work, the code is not even completed.

**Comment by mannprerak2** [comment]
Well, @alexworeku I think you can either create a plugin on your own or go native.
I am closing this issue now.

**Comment by alexworeku** [comment]
Thank you
